# Generated by Django 5.1.5 on 2025-03-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_rename_avatars_user_avatar'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузити фотографию', null=True, upload_to='users/avatar', verbose_name='Аватар'),
        ),
    ]
