[tool.poetry]
name = "django22"
version = "0.1.0"
description = ""
authors = ["fr0st <fr0st1s747@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
automium-web = "^0.1.1"
django = "^5.1.5"
requests-mock = "^1.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
