# Generated by Django 5.1.5 on 2025-02-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateField(blank=True, help_text='Введите датe создания', null=True, verbose_name='дата создания'),
        ),
    ]
