# Generated by Django 5.1.5 on 2025-03-02 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите название', max_length=250, null=True, verbose_name='название')),
                ('description', models.TextField(blank=True, help_text='Введите описание', max_length=250, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=250, verbose_name='название')),
                ('description', models.TextField(help_text='Введите описание', max_length=250, verbose_name='описание')),
                ('image', models.ImageField(blank=True, help_text='Загрузити фотографию', null=True, upload_to='product/photo', verbose_name='фото')),
                ('price', models.IntegerField(blank=True, help_text='Введите цену', null=True, verbose_name='Цена')),
                ('created_at', models.DateField(blank=True, help_text='Введите дату создания', null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата последнего изменения')),
                ('is_available', models.BooleanField(default=False, verbose_name='Доступность в каталоге')),
                ('category', models.ForeignKey(blank=True, help_text='Введите категорию', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'permissions': [('can_unpublish_product', 'Can unpublish product'), ('remove_any_product', 'Remove any product')],
            },
        ),
    ]
