# Generated by Django 5.1.5 on 2025-02-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_created_at_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(blank=True, help_text='Введите датe создания', null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузити фотографию', null=True, upload_to='product/photo', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, help_text='Введите цену', null=True, verbose_name='Цена'),
        ),
    ]
